import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — ContractAudit AI",
};

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-16">
      <h1 className="text-3xl font-display font-bold text-white mb-2">Terms of Service</h1>
      <p className="text-neutral-500 font-mono text-sm mb-12">Last updated: March 2026</p>

      <div className="space-y-10 text-neutral-300 leading-relaxed">
        <section>
          <h2 className="text-lg font-semibold text-white mb-3">1. Acceptance of Terms</h2>
          <p>By accessing or using ContractAudit AI ("Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-3">2. Description of Service</h2>
          <p>ContractAudit AI provides automated static analysis and AI-powered review of Solidity smart contracts. The Service is provided for informational and educational purposes only.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-3">3. No Professional Audit</h2>
          <p className="p-4 border border-amber-500/20 bg-amber-500/5 rounded-lg text-amber-200/80">
            <strong className="text-amber-400">Important Disclaimer:</strong> Reports generated by ContractAudit AI do not constitute a professional security audit. Automated analysis cannot detect all vulnerabilities. You should not deploy contracts handling significant value based solely on this tool's output. Always engage a certified security firm for production contracts.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-3">4. User Accounts</h2>
          <p>You are responsible for maintaining the security of your account credentials. You must not share your account with others or use the Service for unauthorized purposes.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-3">5. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul className="mt-2 space-y-1 list-disc list-inside text-neutral-400">
            <li>Upload malicious or illegal content</li>
            <li>Attempt to circumvent rate limits or billing controls</li>
            <li>Reverse engineer or abuse the API</li>
            <li>Resell or redistribute audit results without attribution</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-3">6. Payment and Billing</h2>
          <p>Paid plans are billed monthly or annually via Stripe. Subscriptions auto-renew unless cancelled. Refunds are considered on a case-by-case basis — contact us at <a href="mailto:support@contractauditor.app" className="text-terminal-green hover:underline">support@contractauditor.app</a>.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-3">7. Intellectual Property</h2>
          <p>The Service and its original content are owned by Full Circle Solutions. You retain ownership of the smart contract source code you submit.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-3">8. Limitation of Liability</h2>
          <p>To the maximum extent permitted by law, ContractAudit AI shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service, including but not limited to losses resulting from smart contract exploits or vulnerabilities not detected by the Service.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-3">9. Changes to Terms</h2>
          <p>We reserve the right to update these terms at any time. Continued use of the Service after changes constitutes acceptance of the new terms.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-3">10. Contact</h2>
          <p>Questions about these terms? Email <a href="mailto:legal@contractauditor.app" className="text-terminal-green hover:underline">legal@contractauditor.app</a></p>
        </section>
      </div>
    </div>
  );
}
